<?php

namespace App\Filament\Resources\RoleResource\Pages;

use App\Filament\Resources\RoleResource;
use App\Models\Permission;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateRole extends CreateRecord
{
    protected static string $resource = RoleResource::class;
    protected static bool $canCreateAnother = false;

    protected function getRedirectUrl(): string
    {
        return $this->previousUrl ?? $this->getResource()::getUrl('index');
    }

    protected function handleRecordCreation(array $data): Model
    {
        $role = static::getModel()::create(['name' => $data['name']]);
        $list_permission = [];

        foreach ($data['permissions'] as $permission) {
            Permission::listPermissionByTitle($permission)->pluck('name')->map(function ($item) use (&$list_permission) {
                $list_permission[] = $item;
            });
        }

        $role->syncPermissions($list_permission);

        return $role; // TODO: Change the autogenerated stub
    }
}
