name: Docker Build and Deploy

on:
  push:
    branches: [ "main" ]  # Sesuaikan dengan branch Anda

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-repo-name:${{ github.sha }}

    - name: Generate SHA256 for Coolify webhook
      id: generate_sha
      run: |
        payload=$(echo -n '{"pusher":{"name":"GitHub Actions"},"after":"'${{ github.sha }}'"}')
        signature=$(echo -n "$payload" | openssl dgst -sha256 -hmac "${{ secrets.COOLIFY_WEBHOOK_SECRET }}" | sed 's/^.* //')
        echo "sha256=$signature" >> $GITHUB_OUTPUT

    - name: Trigger Coolify webhook
      run: |
        curl -X POST ${{ secrets.COOLIFY_WEBHOOK_URL }} \
        -H "Content-Type: application/json" \
        -H "X-Hub-Signature-256: ${{ steps.generate_sha.outputs.sha256 }}" \
        -d '{"pusher":{"name":"GitHub Actions"},"after":"${{ github.sha }}"}'
