name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to VPS
        run: |
          rsync -avz --delete \
          -e 'ssh -o StrictHostKeyChecking=no' \
          ./ root@${{ secrets.FTP_SERVER }}:/home/pengg/financial-report.pengg.web.id/

      - name: Install Composer dependencies
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.FTP_SERVER }} '
          cd /home/pengg/financial-report.pengg.web.id &&
          if [ ! -d "vendor" ]; then
            composer install;
          fi'

      - name: Set Permissions
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.FTP_SERVER }} '
          chown -R www-data:www-data /home/pengg/financial-report.pengg.web.id &&
          chmod -R 775 /home/pengg/financial-report.pengg.web.id'
