name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          rsync -avz --delete \
          -e 'ssh -o StrictHostKeyChecking=no' \
          ./ root@${{ secrets.FTP_SERVER }}:/home/pengg/financial-report.pengg.web.id/

          ssh -o StrictHostKeyChecking=no root@${{ secrets.FTP_SERVER }} << 'EOF'
            cd /home/pengg/financial-report.pengg.web.id

            # Install Composer dependencies if vendor directory does not exist
            if [ ! -d "vendor" ]; then
              composer install
            fi

            #cp .env
            cp /home/pengg/.env.financial-report /home/pengg/financial-report.pengg.web.id/.env
            cp /home/pengg/financial-report.pengg.web.id/resources/assets/*.png /home/pengg/financial-report.pengg.web.id/storage/app/public/

            # Run Laravel migrations
            php artisan migrate --force
            php artisan storage:link

            # Set proper permissions
            chown -R www-data:www-data /home/pengg/financial-report.pengg.web.id
            chmod -R 775 /home/pengg/financial-report.pengg.web.id
          EOF
